config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'services/service'
  devise_for :users
  resources :properties
  resources :measurers
  root to:'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/measurer.rb
class Measurer < ApplicationRecord
  has_and_belongs_to_many :property
end

app/models/measurers_property.rb
class MeasurersProperty < ApplicationRecord
  belongs_to :measurer
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
has_and_belongs_to_many :measurer
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/measurers_controller.rb
class MeasurersController < ApplicationController
  before_action :set_measurer, only: [:show, :edit, :update, :destroy]


  # GET /measurers
  # GET /measurers.json
  def index
    @measurers = Measurer.all
    end

  # GET /measurers/1
  # GET /measurers/1.json
  def show
  end

  # GET /measurers/new
  def new
    @measurer = Measurer.new
  end

  # GET /measurers/1/edit
  def edit
  end

  # POST /measurers
  # POST /measurers.json
  def create
    @measurer = Measurer.new(measurer_params)

    respond_to do |format|
      if @measurer.save
        format.html { redirect_to @measurer, notice: 'Measurer was successfully created.' }
        format.json { render :show, status: :created, location: @measurer }
      else
        format.html { render :new }
        format.json { render json: @measurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurers/1
  # PATCH/PUT /measurers/1.json
  def update
    respond_to do |format|
      if @measurer.update(measurer_params)
        format.html { redirect_to @measurer, notice: 'Measurer was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurer }
      else
        format.html { render :edit }
        format.json { render json: @measurer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurers/1
  # DELETE /measurers/1.json
  def destroy
    @measurer.destroy
    respond_to do |format|
      format.html { redirect_to measurers_url, notice: 'Measurer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurer
      @measurer = Measurer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurer_params
      params.require(:measurer).permit(:id_measure, :name, :uni, :description, :umbrail)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all

  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:id_property, :name, :laste_name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurers_helper.rb
module MeasurersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Condominio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body id="page-top">

      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger far fa-building" href="/">  Building </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link text-white" href="<%=new_user_session_path%>"> Sistema de Login</a>
                <% if user_signed_in? %>
                <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/properties">Propiedades</a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/measurers">Servicios</a>
              </li>
              <div class="dropdown">
                  <a class="nav-link js-scroll-trigger dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Mantenimiento
                  </a>

                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" data-method='DELETE' href="<%=destroy_user_session_path%>">Cerrar Session</a>
                  </div>
                </div>
                <% end %>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/measurers/_form.html.erb
<%= form_with(model: measurer, local: true) do |form| %>
  <% if measurer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measurer.errors.count, "error") %> prohibited this measurer from being saved:</h2>

      <ul>
      <% measurer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <strong>Numero de Servicio:</strong>
    <%form.label :id_measure %>
    <%= form.number_field :id_measure, class:"form-control", placeholder:"Ingresar Numero de Servicio"%>
  </div>

  <div class="field">
  <strong>Nombre Servicio:</strong>
    <%form.label :name %>
    <%= form.text_field :name , class:"form-control", placeholder:"Nombre del Servicio"%>
  </div>

  <div class="field">
  <strong>Metros Cuadrados</strong>
    <% form.label :unin%>
    <%= form.text_field :uni, class:"form-control", placeholder:"M3"%>
  </div>

  <div class="field">
  <strong>Descripcion:</strong>
    <% form.label :description%>
    <%= form.text_field :description, class:"form-control", placeholder:"Descripcion"%>
  </div>

  <div class="field">
  <strong>Umbral de sobreconsumo</strong>
    <% form.label :umbrail %>
    <%= form.number_field :umbrail, class:"form-control", placeholder:"10,00"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/measurers/edit.html.erb
<h1>Editar Servicios</h1>

<%= render 'form', measurer: @measurer %>

<%= link_to 'Show', @measurer %> |
<%= link_to 'Back', measurers_path %>

app/views/measurers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Servicios</h1>

<div class="row">
<div class="col">
<table class="table table-hover table-bordered ">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>Servicio</th>
      <th>Unidad de Medidas</th>
      <th>Descripcion</th>
      <th>Umbrail Sobre Consumo</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measurers.each do |measurer| %>
      <tr>
        <td><%= measurer.id_measure %></td>
        <td><%= measurer.name %></td>
        <td><%= measurer.uni %></td>
        <td><%= measurer.description %></td>
        <td><%= measurer.umbrail %></td>
        <td><%= link_to ' Editar', edit_measurer_path(measurer), class: " btn bg-primary far fa-address-card" %></td>
        <td><%= link_to 'Eliminar', measurer, class:"btn bg-danger far fa-trash-undo-alt", method: :delete, data: { confirm: 'Confirma para eliminar?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Agregar Servicio', new_measurer_path, class: "btn bg-info far fa-building"%>

app/views/measurers/new.html.erb
<h1>Nuevo Servicio</h1>

<%= render 'form', measurer: @measurer%>
<br/>
<%= link_to 'Salir', measurers_path, class:"btn btn-outline-secondary" %>

app/views/measurers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id measure:</strong>
  <%= @measurer.id_measure %>
</p>

<p>
  <strong>Name:</strong>
  <%= @measurer.name %>
</p>

<p>
  <strong>Uni:</strong>
  <%= @measurer.uni %>
</p>

<p>
  <strong>Description:</strong>
  <%= @measurer.description %>
</p>

<p>
  <strong>Umbrail:</strong>
  <%= @measurer.umbrail %>
</p>

<%= link_to 'Edit', edit_measurer_path(@measurer) %> |
<%= link_to 'Salir', measurers_path, class:"btn btn-outline-secondary" %>

app/views/pages/index.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <header class="bg-primary text-white">
    <div class="container text-center">
      <h1>Sistema Administrativo Condominio</h1>
      <p class="lead">Sistema de Administración de Condominio
ISAC, Sistema de Administracion de Condominio con envío de recibos de condominio mediante Email</p>
    </div>
  </header>
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2>About this page</h2>
          <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
		  <ul>

            <li>Clickable nav links that smooth scroll to page sections</li>
            <li>Responsive behavior when clicking nav links perfect for a one page website</li>
            <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
            <li>Minimal custom CSS so you are free to explore your own unique design options</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="box">
    <div class="container">
     	<div class="row py-5">

			    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

                        <i class="far fa-envelope-open-dollar fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Instagram</h4>
						</div>

						<div class="text">
							<span>Ahorro garantizado en la hora de envío de los Recibos de Condominio o Avisos de Cobro.</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

					    <i class="fas fa-building fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Condominio</h4>
						</div>

						<div class="text">
							<span>Reducción de tiempo en la gestión de sus comunicaciones</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

                        <i class="fa fa-facebook fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Facebook</h4>
						</div>

						<div class="text">
							<span>Se crea perfiles de Administradora y de Propietarios</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

                        <i class="fa fa-pinterest-p fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Pinterest</h4>
						</div>

						<div class="text">
							<span> El propietario, ve su información, ve la cartelera, agrega los pagos, y ve sus recibos de condominio</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

					    <i class="fas fa-ruble-sign fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Money</h4>
						</div>

						<div class="text">
							<span>Realizarse en tan sólo unos minutos, desde cualquier parte del mundo</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

				 <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

					<div class="box-part text-center">

                        <i class="fa fa-github fa-3x" aria-hidden="true"></i>

						<div class="title">
							<h4>Github</h4>
						</div>

						<div class="text">
							<span>Lorem ipsum dolor sit amet, id quo eruditi eloquentiam. Assum decore te sed. Elitr scripta ocurreret qui ad.</span>
						</div>

						<a href="#">Learn More</a>

					 </div>
				</div>

		</div>
    </div>
</div>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Sistema de Administración de Condominio</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Plugin JavaScript -->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom JavaScript for this theme -->
  <script src="js/scrolling-nav.js"></script>

</body>

</html>

app/views/properties/_form.html.erb
<%= form_with(model: @property, local: true) do |form| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <strong>Numero de propiedad:</strong>
    <%form.label :id_property%>
    <%= form.number_field :id_property, class:"form-control", placeholder:"Numero de Propiedad"%>

  <div class="field">
  <strong>Nombre:</strong>
    <%form.label :name %>
    <%= form.text_field :name , class:"form-control", placeholder:"Nombre del Propietario"%>
  </div>

  <div class="field">
  <strong>Apellido:</strong>
    <%form.label :laste_name %>
    <%= form.text_field :laste_name, class:"form-control", placeholder:"Apellido del Propietario"%>
  </div>

  <div class="field">
  <strong>Correo Electronico:</strong>
    <% form.label :description%>
    <%= form.text_field :description, class:"form-control", placeholder:"Correo Electronico"%>
  </div>

  <div class="actions">
    <%=form.submit%>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Salir', properties_path, class:"btn btn-outline-secondary" %>

app/views/properties/index.html.erb
<h1>Lista de Propiedades</h1>

<%= link_to 'Nueva propiedad', new_property_path, class: "btn btn-primary far fa-building"%>
</br>

<div class="row">
<div class="col">
<table class="table table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Numero de Propiedad</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido</th>
      <th scope="col">Correo Electronico</th>
    </tr>
  </thead>
  <tbody>
  <% @properties.each do |property| %>
    <tr>
      <td><%= property.id_property %></td>
      <td><%= property.name %></td>
      <td><%= property.laste_name%></td>
      <td><%= property.description %></td>
      <td><%= link_to 'Ver', property, class: " btn btn-info far fa-eye" %></td>
      <td><%= link_to 'Editar', edit_property_path(property), class: "btn btn-success far fa-address-card"%></td>
      <!--<td><% link_to 'Destroy',property, method: :delete, data: { confirm: 'Are you sure?' }%></td>-->
    </tr>
  <% end %>
</tbody>
</table>
<br>
</div>
</div>

app/views/properties/new.html.erb
<h1>Registro de Nueva Propiedad</h1>

<%= render 'form', property: @property %>

<br/>
<%= link_to 'Salir', properties_path, class:"btn btn-outline-secondary" %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id property:</strong>
  <%= @property.id_property %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @property.laste_name%>
</p>


<p>
  <strong>Correo Electronico:</strong>
  <%= @property.description %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Salir', properties_path, class:"btn btn-outline-secondary" %>